//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignOfEffectiveLenghtOfColumns {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralRes() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesignOfEffectiveLenghtOfColumns.GeneralRes", typeof(GeneralRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание!.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип опирания стойки.
        /// </summary>
        internal static string BearingOfColumn {
            get {
                return ResourceManager.GetString("BearingOfColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опирание стропильных конструкций.
        /// </summary>
        internal static string BearingOfRafter {
            get {
                return ResourceManager.GetString("BearingOfRafter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опирание колонн на фундамент.
        /// </summary>
        internal static string BearingType {
            get {
                return ResourceManager.GetString("BearingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BottomCrossbracing_RigidBearing {
            get {
                object obj = ResourceManager.GetObject("BottomCrossbracing_RigidBearing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BottomCrossbracing_SwivelBearing {
            get {
                object obj = ResourceManager.GetObject("BottomCrossbracing_SwivelBearing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BottomCrossbracingSwivelBearing {
            get {
                object obj = ResourceManager.GetObject("BottomCrossbracingSwivelBearing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на нижний.
        /// </summary>
        internal static string BottomStorey {
            get {
                return ResourceManager.GetString("BottomStorey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c.
        /// </summary>
        internal static string c {
            get {
                return ResourceManager.GetString("c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на см4.
        /// </summary>
        internal static string cm4 {
            get {
                return ResourceManager.GetString("cm4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коэффициент.
        /// </summary>
        internal static string Coefficient {
            get {
                return ResourceManager.GetString("Coefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коэффициент расчетной длины.
        /// </summary>
        internal static string CoeffOfEffectLength {
            get {
                return ResourceManager.GetString("CoeffOfEffectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Column_BottomCrossbracing_RigidBearing {
            get {
                object obj = ResourceManager.GetObject("Column_BottomCrossbracing_RigidBearing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Column_BottomCrossbracing_SwivelBearing {
            get {
                object obj = ResourceManager.GetObject("Column_BottomCrossbracing_SwivelBearing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Column_MultipleSpans_RigidBearingOfRafter {
            get {
                object obj = ResourceManager.GetObject("Column_MultipleSpans_RigidBearingOfRafter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Column_MultipleSpans_SwivelBearingOfRafter {
            get {
                object obj = ResourceManager.GetObject("Column_MultipleSpans_SwivelBearingOfRafter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Column_OneSpan_RigidBearingOfRafter {
            get {
                object obj = ResourceManager.GetObject("Column_OneSpan_RigidBearingOfRafter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Column_OneSpan_SwivelBearingOfRafter {
            get {
                object obj = ResourceManager.GetObject("Column_OneSpan_SwivelBearingOfRafter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Column_TopCrossbracing_RigidBearing {
            get {
                object obj = ResourceManager.GetObject("Column_TopCrossbracing_RigidBearing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Column_TopCrossbracing_SwivelBearing {
            get {
                object obj = ResourceManager.GetObject("Column_TopCrossbracing_SwivelBearing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Колонны постоянного сечения.
        /// </summary>
        internal static string ColumnsOfConstantSection {
            get {
                return ResourceManager.GetString("ColumnsOfConstantSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Колонны с неполной связью.
        /// </summary>
        internal static string ColumnWithIncompleteCoupling {
            get {
                return ResourceManager.GetString("ColumnWithIncompleteCoupling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рассматриваемая колонна.
        /// </summary>
        internal static string ConcernedColumn {
            get {
                return ResourceManager.GetString("ConcernedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рассматриваемый этаж.
        /// </summary>
        internal static string ConcernedStorey {
            get {
                return ResourceManager.GetString("ConcernedStorey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расчет.
        /// </summary>
        internal static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Определение расчетной длины металлических колонн.
        /// </summary>
        internal static string DeterminationOfEffectiveLengthOfSteelColumns {
            get {
                return ResourceManager.GetString("DeterminationOfEffectiveLengthOfSteelColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Те же данные,
        ///что и слева.
        /// </summary>
        internal static string DuplicateLeftToRight {
            get {
                return ResourceManager.GetString("DuplicateLeftToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расчетная длина колонны.
        /// </summary>
        internal static string EffectiveLenghtOfColumn {
            get {
                return ResourceManager.GetString("EffectiveLenghtOfColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расчетная длина.
        /// </summary>
        internal static string EffectLength {
            get {
                return ResourceManager.GetString("EffectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расчетная длина (µ * h).
        /// </summary>
        internal static string EffectLengthMuOnH {
            get {
                return ResourceManager.GetString("EffectLengthMuOnH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon EffLength {
            get {
                object obj = ResourceManager.GetObject("EffLength", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите число..
        /// </summary>
        internal static string EnterANumber {
            get {
                return ResourceManager.GetString("EnterANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на крайняя.
        /// </summary>
        internal static string ExtermeColumn {
            get {
                return ResourceManager.GetString("ExtermeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на F1.
        /// </summary>
        internal static string F1 {
            get {
                return ResourceManager.GetString("F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на F2.
        /// </summary>
        internal static string F2 {
            get {
                return ResourceManager.GetString("F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значения F2 и F1 не могут одновременно равняться нулю!.
        /// </summary>
        internal static string F2andF1CanNotEqualZero {
            get {
                return ResourceManager.GetString("F2andF1CanNotEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нагрузка.
        /// </summary>
        internal static string Force {
            get {
                return ResourceManager.GetString("Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Frame_BottomCrossbracing_RigidBearing {
            get {
                object obj = ResourceManager.GetObject("Frame_BottomCrossbracing_RigidBearing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Frame_BottomCrossbracing_SwivelBearing {
            get {
                object obj = ResourceManager.GetObject("Frame_BottomCrossbracing_SwivelBearing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Frame_MultipleSpans_RigidBearingOfRafter {
            get {
                object obj = ResourceManager.GetObject("Frame_MultipleSpans_RigidBearingOfRafter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Frame_MultipleSpans_SwivelBearingOfRafter {
            get {
                object obj = ResourceManager.GetObject("Frame_MultipleSpans_SwivelBearingOfRafter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Frame_OneSpan_RigidBearingOfRafter {
            get {
                object obj = ResourceManager.GetObject("Frame_OneSpan_RigidBearingOfRafter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Frame_OneSpan_SwivelBearingOfRafter {
            get {
                object obj = ResourceManager.GetObject("Frame_OneSpan_SwivelBearingOfRafter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Frame_TopCrossbracing_RigidBearing {
            get {
                object obj = ResourceManager.GetObject("Frame_TopCrossbracing_RigidBearing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Frame_TopCrossbracing_SwivelBearing {
            get {
                object obj = ResourceManager.GetObject("Frame_TopCrossbracing_SwivelBearing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип рамы.
        /// </summary>
        internal static string FrameType {
            get {
                return ResourceManager.GetString("FrameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на свободная.
        /// </summary>
        internal static string FreeFrame {
            get {
                return ResourceManager.GetString("FreeFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высота свободной части.
        /// </summary>
        internal static string FreeHeight {
            get {
                return ResourceManager.GetString("FreeHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FreeMultiplestoreysBottomstoreyRigidbearingExterme {
            get {
                object obj = ResourceManager.GetObject("FreeMultiplestoreysBottomstoreyRigidbearingExterme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FreeMultiplestoreysBottomstoreyRigidbearingMiddle {
            get {
                object obj = ResourceManager.GetObject("FreeMultiplestoreysBottomstoreyRigidbearingMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FreeMultiplestoreysBottomstoreySwivelbearingExterme {
            get {
                object obj = ResourceManager.GetObject("FreeMultiplestoreysBottomstoreySwivelbearingExterme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FreeMultiplestoreysBottomstoreySwivelbearingMiddle {
            get {
                object obj = ResourceManager.GetObject("FreeMultiplestoreysBottomstoreySwivelbearingMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FreeMultiplestoreysMiddlestoreyExterme {
            get {
                object obj = ResourceManager.GetObject("FreeMultiplestoreysMiddlestoreyExterme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FreeMultiplestoreysMiddlestoreyMiddle {
            get {
                object obj = ResourceManager.GetObject("FreeMultiplestoreysMiddlestoreyMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FreeMultiplestoreysTopstoreyExterme {
            get {
                object obj = ResourceManager.GetObject("FreeMultiplestoreysTopstoreyExterme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FreeMultiplestoreysTopstoreyMiddle {
            get {
                object obj = ResourceManager.GetObject("FreeMultiplestoreysTopstoreyMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FreeOnestoreyRigidbearingExterme {
            get {
                object obj = ResourceManager.GetObject("FreeOnestoreyRigidbearingExterme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FreeOnestoreyRigidbearingMiddle {
            get {
                object obj = ResourceManager.GetObject("FreeOnestoreyRigidbearingMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FreeOnestoreySwivelbearingExterme {
            get {
                object obj = ResourceManager.GetObject("FreeOnestoreySwivelbearingExterme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FreeOnestoreySwivelbearingMiddle {
            get {
                object obj = ResourceManager.GetObject("FreeOnestoreySwivelbearingMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полная высота.
        /// </summary>
        internal static string FullHeight {
            get {
                return ResourceManager.GetString("FullHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на h.
        /// </summary>
        internal static string h {
            get {
                return ResourceManager.GetString("h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на h1.
        /// </summary>
        internal static string h1 {
            get {
                return ResourceManager.GetString("h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на h2.
        /// </summary>
        internal static string h2 {
            get {
                return ResourceManager.GetString("h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высота.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I1.
        /// </summary>
        internal static string I1 {
            get {
                return ResourceManager.GetString("I1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I2.
        /// </summary>
        internal static string I2 {
            get {
                return ResourceManager.GetString("I2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ic.
        /// </summary>
        internal static string Ic {
            get {
                return ResourceManager.GetString("Ic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ic/Ii.
        /// </summary>
        internal static string IcOnIi {
            get {
                return ResourceManager.GetString("IcOnIi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ic/Ii1.
        /// </summary>
        internal static string IcOnIi1 {
            get {
                return ResourceManager.GetString("IcOnIi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ic/Ii2.
        /// </summary>
        internal static string IcOnIi2 {
            get {
                return ResourceManager.GetString("IcOnIi2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ic/Is.
        /// </summary>
        internal static string IcOnIs {
            get {
                return ResourceManager.GetString("IcOnIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ic/Is1.
        /// </summary>
        internal static string IcOnIs1 {
            get {
                return ResourceManager.GetString("IcOnIs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ic/Is2.
        /// </summary>
        internal static string IcOnIs2 {
            get {
                return ResourceManager.GetString("IcOnIs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ii.
        /// </summary>
        internal static string Ii {
            get {
                return ResourceManager.GetString("Ii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ii1.
        /// </summary>
        internal static string Ii1 {
            get {
                return ResourceManager.GetString("Ii1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ii2.
        /// </summary>
        internal static string Ii2 {
            get {
                return ResourceManager.GetString("Ii2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректно заданное значение..
        /// </summary>
        internal static string IncorrectValue {
            get {
                return ResourceManager.GetString("IncorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is.
        /// </summary>
        internal static string Is {
            get {
                return ResourceManager.GetString("Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is1.
        /// </summary>
        internal static string Is1 {
            get {
                return ResourceManager.GetString("Is1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is2.
        /// </summary>
        internal static string Is2 {
            get {
                return ResourceManager.GetString("Is2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на k.
        /// </summary>
        internal static string k {
            get {
                return ResourceManager.GetString("k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на l.
        /// </summary>
        internal static string l {
            get {
                return ResourceManager.GetString("l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на l1.
        /// </summary>
        internal static string l1 {
            get {
                return ResourceManager.GetString("l1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на l2.
        /// </summary>
        internal static string l2 {
            get {
                return ResourceManager.GetString("l2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на lef.
        /// </summary>
        internal static string lef {
            get {
                return ResourceManager.GetString("lef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на lef1.
        /// </summary>
        internal static string lef1 {
            get {
                return ResourceManager.GetString("lef1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на lef2.
        /// </summary>
        internal static string lef2 {
            get {
                return ResourceManager.GetString("lef2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на м.
        /// </summary>
        internal static string m {
            get {
                return ResourceManager.GetString("m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на средняя.
        /// </summary>
        internal static string MiddleColumn {
            get {
                return ResourceManager.GetString("MiddleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на средний.
        /// </summary>
        internal static string MiddleStorey {
            get {
                return ResourceManager.GetString("MiddleStorey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Момент инерции.
        /// </summary>
        internal static string MomInert {
            get {
                return ResourceManager.GetString("MomInert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Момент инерции нижнего ригеля.
        /// </summary>
        internal static string MomInertOfBottomGirder {
            get {
                return ResourceManager.GetString("MomInertOfBottomGirder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Момент инерции колонны.
        /// </summary>
        internal static string MomInertOfColumn {
            get {
                return ResourceManager.GetString("MomInertOfColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Момент инерции ригеля.
        /// </summary>
        internal static string MomInertOfGirder {
            get {
                return ResourceManager.GetString("MomInertOfGirder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Момент инерции верхнего ригеля.
        /// </summary>
        internal static string MomInertOfUpperGirder {
            get {
                return ResourceManager.GetString("MomInertOfUpperGirder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соотношение между жест-
        ///костью колонны и ригеля.
        /// </summary>
        internal static string MomInetrtRatioOneGirder {
            get {
                return ResourceManager.GetString("MomInetrtRatioOneGirder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соотношение между жест-
        ///костью колонны и ригелей.
        /// </summary>
        internal static string MomInetrtRatioTwoGirders {
            get {
                return ResourceManager.GetString("MomInetrtRatioTwoGirders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на µ.
        /// </summary>
        internal static string mu {
            get {
                return ResourceManager.GetString("mu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на µ1.
        /// </summary>
        internal static string mu1 {
            get {
                return ResourceManager.GetString("mu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на µ2.
        /// </summary>
        internal static string mu2 {
            get {
                return ResourceManager.GetString("mu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на два и более.
        /// </summary>
        internal static string multipleSpans {
            get {
                return ResourceManager.GetString("multipleSpans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на многоэтажная.
        /// </summary>
        internal static string MultipleStoreys {
            get {
                return ResourceManager.GetString("MultipleStoreys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на должны быть больше нуля!.
        /// </summary>
        internal static string mustBeGreaterThanZeroPlural {
            get {
                return ResourceManager.GetString("mustBeGreaterThanZeroPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на должно быть больше нуля!.
        /// </summary>
        internal static string mustBeGreaterThanZeroSingle {
            get {
                return ResourceManager.GetString("mustBeGreaterThanZeroSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не является числом!.
        /// </summary>
        internal static string NotANumber {
            get {
                return ResourceManager.GetString("NotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не являются числами!.
        /// </summary>
        internal static string NotANumbers {
            get {
                return ResourceManager.GetString("NotANumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не задано значение для.
        /// </summary>
        internal static string NotDefineValueFor {
            get {
                return ResourceManager.GetString("NotDefineValueFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не заданы значения для.
        /// </summary>
        internal static string NotDefineValuesFor {
            get {
                return ResourceManager.GetString("NotDefineValuesFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во пролетов.
        /// </summary>
        internal static string NumberOfSpans {
            get {
                return ResourceManager.GetString("NumberOfSpans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество полетов должно быть не менее двух!.
        /// </summary>
        internal static string NumberOfSpansShallBeAtLeastTwo {
            get {
                return ResourceManager.GetString("NumberOfSpansShallBeAtLeastTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этажность.
        /// </summary>
        internal static string NumberOfStoreys {
            get {
                return ResourceManager.GetString("NumberOfStoreys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество пролетов не является целым числом!.
        /// </summary>
        internal static string NumOfSpansNotWholeNumber {
            get {
                return ResourceManager.GetString("NumOfSpansNotWholeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на один.
        /// </summary>
        internal static string oneSpan {
            get {
                return ResourceManager.GetString("oneSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на одноэтажная.
        /// </summary>
        internal static string OneStorey {
            get {
                return ResourceManager.GetString("OneStorey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры нижнего участка.
        /// </summary>
        internal static string ParamOfBottomPart {
            get {
                return ResourceManager.GetString("ParamOfBottomPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры стойки.
        /// </summary>
        internal static string ParamOfColumn {
            get {
                return ResourceManager.GetString("ParamOfColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры верхнего участка.
        /// </summary>
        internal static string ParamOfTopPart {
            get {
                return ResourceManager.GetString("ParamOfTopPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры рамы.
        /// </summary>
        internal static string ParamsOfFrame {
            get {
                return ResourceManager.GetString("ParamsOfFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры рамы слева от рассматриваемой колонны.
        /// </summary>
        internal static string ParamsOfFrameOnLeft {
            get {
                return ResourceManager.GetString("ParamsOfFrameOnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры рамы справа от рассматриваемой колонны.
        /// </summary>
        internal static string ParamsOfFrameOnRight {
            get {
                return ResourceManager.GetString("ParamsOfFrameOnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pic_BottomCrossbracing {
            get {
                object obj = ResourceManager.GetObject("Pic_BottomCrossbracing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pic_TopCrossbracing {
            get {
                object obj = ResourceManager.GetObject("Pic_TopCrossbracing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расположение  связи.
        /// </summary>
        internal static string PositionOfCrossbrace {
            get {
                return ResourceManager.GetString("PositionOfCrossbrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соотношение длины верхней и нижней части (l2/l1) меньше нижнего предела (0.1)..
        /// </summary>
        internal static string RatioOfLengthExceedBottomLimit {
            get {
                return ResourceManager.GetString("RatioOfLengthExceedBottomLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соотношение высоты верхней и нижней части (h2/h1) меньше нижнего предела (0.01)..
        /// </summary>
        internal static string RatioOfLengthExceedBottomLimitColumnWithIncompleteCoupling {
            get {
                return ResourceManager.GetString("RatioOfLengthExceedBottomLimitColumnWithIncompleteCoupling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соотношение длины верхней и нижней части (l2/l1) больше верхнего предела (2.0)..
        /// </summary>
        internal static string RatioOfLengthExceedTopLimit {
            get {
                return ResourceManager.GetString("RatioOfLengthExceedTopLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соотношение высоты верхней и нижней части (h2/h1) больше верхнего предела (100)..
        /// </summary>
        internal static string RatioOfLengthExceedTopLimitColumnWithIncompleteCoupling {
            get {
                return ResourceManager.GetString("RatioOfLengthExceedTopLimitColumnWithIncompleteCoupling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соотношение погонной жесткости верхней и нижней части (I2/l2)/(I1/l1) выше допустимого..
        /// </summary>
        internal static string RatioOfLinearRigidityExceedLimit {
            get {
                return ResourceManager.GetString("RatioOfLinearRigidityExceedLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соотношение жесткости верхней и нижней части (I2/I1) меньше нижнего предела (0.04)..
        /// </summary>
        internal static string RatioOfRigidityExceedBottomLimit {
            get {
                return ResourceManager.GetString("RatioOfRigidityExceedBottomLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соотношение жесткости верхней и нижней части (I2/I1) меньше нижнего предела (0.01)..
        /// </summary>
        internal static string RatioOfRigidityExceedBottomLimitColumnWithIncompleteCoupling {
            get {
                return ResourceManager.GetString("RatioOfRigidityExceedBottomLimitColumnWithIncompleteCoupling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соотношение жесткости верхней и нижней части (I2/I1) больше верхнего предела (1.0)..
        /// </summary>
        internal static string RatioOfRigidityExceedTopLimit {
            get {
                return ResourceManager.GetString("RatioOfRigidityExceedTopLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соотношение жесткости верхней и нижней части (I2/I1) больше верхнего предела (16)..
        /// </summary>
        internal static string RatioOfRigidityExceedTopLimitColumnWithIncompleteCoupling {
            get {
                return ResourceManager.GetString("RatioOfRigidityExceedTopLimitColumnWithIncompleteCoupling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результаты.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результаты для нижнего участка.
        /// </summary>
        internal static string ResultsOfBottomPart {
            get {
                return ResourceManager.GetString("ResultsOfBottomPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результаты для верхнего участка.
        /// </summary>
        internal static string ResultsOfTopPart {
            get {
                return ResourceManager.GetString("ResultsOfTopPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на жесткое    .
        /// </summary>
        internal static string rigidBearing {
            get {
                return ResourceManager.GetString("rigidBearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Решение не найдено!.
        /// </summary>
        internal static string SolutionNotFound {
            get {
                return ResourceManager.GetString("SolutionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пролет.
        /// </summary>
        internal static string Span {
            get {
                return ResourceManager.GetString("Span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ступенчатые колонны.
        /// </summary>
        internal static string SteppedColumns {
            get {
                return ResourceManager.GetString("SteppedColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на шарнирное.
        /// </summary>
        internal static string swivelBearing {
            get {
                return ResourceManager.GetString("swivelBearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на тс.
        /// </summary>
        internal static string tf {
            get {
                return ResourceManager.GetString("tf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TopCrossbracing_RigidBearing {
            get {
                object obj = ResourceManager.GetObject("TopCrossbracing_RigidBearing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TopCrossbracing_SwivelBearing {
            get {
                object obj = ResourceManager.GetObject("TopCrossbracing_SwivelBearing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на верхний.
        /// </summary>
        internal static string TopStorey {
            get {
                return ResourceManager.GetString("TopStorey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на несвободная.
        /// </summary>
        internal static string UnfreeFrame {
            get {
                return ResourceManager.GetString("UnfreeFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnfreeMultiplestoreysBottomstoreyRigidbearingExterme {
            get {
                object obj = ResourceManager.GetObject("UnfreeMultiplestoreysBottomstoreyRigidbearingExterme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnfreeMultiplestoreysBottomstoreyRigidbearingMiddle {
            get {
                object obj = ResourceManager.GetObject("UnfreeMultiplestoreysBottomstoreyRigidbearingMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnfreeMultiplestoreysBottomstoreySwivelbearingExterme {
            get {
                object obj = ResourceManager.GetObject("UnfreeMultiplestoreysBottomstoreySwivelbearingExterme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnfreeMultiplestoreysBottomstoreySwivelbearingMiddle {
            get {
                object obj = ResourceManager.GetObject("UnfreeMultiplestoreysBottomstoreySwivelbearingMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnfreeMultiplestoreysMiddlestoreyExterme {
            get {
                object obj = ResourceManager.GetObject("UnfreeMultiplestoreysMiddlestoreyExterme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnfreeMultiplestoreysMiddlestoreyMiddle {
            get {
                object obj = ResourceManager.GetObject("UnfreeMultiplestoreysMiddlestoreyMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnfreeMultiplestoreysTopstoreyExterme {
            get {
                object obj = ResourceManager.GetObject("UnfreeMultiplestoreysTopstoreyExterme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnfreeMultiplestoreysTopstoreyMiddle {
            get {
                object obj = ResourceManager.GetObject("UnfreeMultiplestoreysTopstoreyMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnfreeOnestoreyRigidbearingExterme {
            get {
                object obj = ResourceManager.GetObject("UnfreeOnestoreyRigidbearingExterme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnfreeOnestoreyRigidbearingMiddle {
            get {
                object obj = ResourceManager.GetObject("UnfreeOnestoreyRigidbearingMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnfreeOnestoreySwivelbearingExterme {
            get {
                object obj = ResourceManager.GetObject("UnfreeOnestoreySwivelbearingExterme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnfreeOnestoreySwivelbearingMiddle {
            get {
                object obj = ResourceManager.GetObject("UnfreeOnestoreySwivelbearingMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение c должно быть менее h!.
        /// </summary>
        internal static string ValueOfCCanNotBeLessOfH {
            get {
                return ResourceManager.GetString("ValueOfCCanNotBeLessOfH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значения.
        /// </summary>
        internal static string Values {
            get {
                return ResourceManager.GetString("Values", resourceCulture);
            }
        }
    }
}
